# Generated by Django 6.0.3 on 2026-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_company_review_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default='TBD', max_length=255),
            preserve_default=False,
        ),
    ]
