# Generated by Django 6.0.3 on 2026-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_company_listing_profilecomment_vacancy_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(),
        ),
    ]
