# Generated by Django 2.2.28 on 2026-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_company_location_vacancy_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('job_type', models.CharField(choices=[('entry_level', 'Entry-Level Job'), ('internship', 'Internship')], default='internship', max_length=20)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
