# Generated by Django 5.2.12 on 2026-03-24 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum.vacancy",
            ),
        ),
    ]
