# Generated by Django 6.0.3 on 2026-03-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_listing_profilecomment_delete_review'),
        ('forum', '0008_alter_comment_unique_together_alter_comment_vacancy_and_more'),
    ]

    operations = [
    ]
